project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "about.qmd"
    - "eda-basic.qmd"
    - "model-basic-py.qmd"

website:
  title: "Devops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda-basic.qmd
        text: EDA
      - href: model-basic-py.qmd
        text: Model
      - href: about.qmd
        text: About
    collapse: true

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

