services:
  api:
    hostname: myapi
    build: ./api
    image: devops-api
    command: python runapi.py
    ports:
      - 8080:8080

  app:
    hostname: myapp
    build: ./app
    image: devops-app
    command: python app-log.py
    ports:
      - 8090:8090

  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docs:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    restart: always
    environment:
      - HOSTNAME=devops.cometto.org

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw