services:
  api:
    hostname: myapi
    build: ./api
    image: devops-api
    command: python runapi.py
    ports:
      - 8080:8080

  app:
    hostname: myapp
    build: ./app
    image: devops-app
    command: python app-log.py
    ports:
      - 8090:8090

  web:
    build: ./web
    image: devops-web
    ports:
      - 8095:80
    volumes:
      - ./docs:/usr/share/nginx/html
    environment:
      - SETHOSTNAME=localhost