version: '3'

services:

  api:
    hostname: myapi
    build: ./api
    image: devops-api
    command: python runapi.py

  app:
    hostname: myapp
    build: ./app
    image: devops-app
    command: python app-log.py
    ports: 
      - 8091:8090

  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - 8090:8090
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf:/etc/nginx/ssl/

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  web:
    build: ./web
    image: devops-web
    ports:
      - 8095:80
    volumes:
      - ./docker-volumes/docs:/usr/share/nginx/html